/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.ComputeInfoForInBuilt;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.OperationName;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Compute Info For In Built</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ComputeInfoForInBuiltImpl#getOperationName <em>Operation Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ComputeInfoForInBuiltImpl#getOperationParameter <em>Operation Parameter</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComputeInfoForInBuiltImpl extends MinimalEObjectImpl.Container implements ComputeInfoForInBuilt
{
  /**
   * The cached value of the '{@link #getOperationName() <em>Operation Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperationName()
   * @generated
   * @ordered
   */
  protected OperationName operationName;

  /**
   * The default value of the '{@link #getOperationParameter() <em>Operation Parameter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperationParameter()
   * @generated
   * @ordered
   */
  protected static final int OPERATION_PARAMETER_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getOperationParameter() <em>Operation Parameter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperationParameter()
   * @generated
   * @ordered
   */
  protected int operationParameter = OPERATION_PARAMETER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComputeInfoForInBuiltImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.COMPUTE_INFO_FOR_IN_BUILT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OperationName getOperationName()
  {
    return operationName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOperationName(OperationName newOperationName, NotificationChain msgs)
  {
    OperationName oldOperationName = operationName;
    operationName = newOperationName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.COMPUTE_INFO_FOR_IN_BUILT__OPERATION_NAME, oldOperationName, newOperationName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOperationName(OperationName newOperationName)
  {
    if (newOperationName != operationName)
    {
      NotificationChain msgs = null;
      if (operationName != null)
        msgs = ((InternalEObject)operationName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.COMPUTE_INFO_FOR_IN_BUILT__OPERATION_NAME, null, msgs);
      if (newOperationName != null)
        msgs = ((InternalEObject)newOperationName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.COMPUTE_INFO_FOR_IN_BUILT__OPERATION_NAME, null, msgs);
      msgs = basicSetOperationName(newOperationName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.COMPUTE_INFO_FOR_IN_BUILT__OPERATION_NAME, newOperationName, newOperationName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getOperationParameter()
  {
    return operationParameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOperationParameter(int newOperationParameter)
  {
    int oldOperationParameter = operationParameter;
    operationParameter = newOperationParameter;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.COMPUTE_INFO_FOR_IN_BUILT__OPERATION_PARAMETER, oldOperationParameter, operationParameter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.COMPUTE_INFO_FOR_IN_BUILT__OPERATION_NAME:
        return basicSetOperationName(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.COMPUTE_INFO_FOR_IN_BUILT__OPERATION_NAME:
        return getOperationName();
      case MyDslPackage.COMPUTE_INFO_FOR_IN_BUILT__OPERATION_PARAMETER:
        return getOperationParameter();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.COMPUTE_INFO_FOR_IN_BUILT__OPERATION_NAME:
        setOperationName((OperationName)newValue);
        return;
      case MyDslPackage.COMPUTE_INFO_FOR_IN_BUILT__OPERATION_PARAMETER:
        setOperationParameter((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.COMPUTE_INFO_FOR_IN_BUILT__OPERATION_NAME:
        setOperationName((OperationName)null);
        return;
      case MyDslPackage.COMPUTE_INFO_FOR_IN_BUILT__OPERATION_PARAMETER:
        setOperationParameter(OPERATION_PARAMETER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.COMPUTE_INFO_FOR_IN_BUILT__OPERATION_NAME:
        return operationName != null;
      case MyDslPackage.COMPUTE_INFO_FOR_IN_BUILT__OPERATION_PARAMETER:
        return operationParameter != OPERATION_PARAMETER_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (operationParameter: ");
    result.append(operationParameter);
    result.append(')');
    return result.toString();
  }

} //ComputeInfoForInBuiltImpl
