/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.EventConditions;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Unit;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Event Conditions</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.EventConditionsImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.EventConditionsImpl#getIntValue <em>Int Value</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.EventConditionsImpl#getNameUnit <em>Name Unit</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.EventConditionsImpl#getEventConditions <em>Event Conditions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EventConditionsImpl extends MinimalEObjectImpl.Container implements EventConditions
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getIntValue() <em>Int Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntValue()
   * @generated
   * @ordered
   */
  protected static final int INT_VALUE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getIntValue() <em>Int Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntValue()
   * @generated
   * @ordered
   */
  protected int intValue = INT_VALUE_EDEFAULT;

  /**
   * The cached value of the '{@link #getNameUnit() <em>Name Unit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNameUnit()
   * @generated
   * @ordered
   */
  protected Unit nameUnit;

  /**
   * The cached value of the '{@link #getEventConditions() <em>Event Conditions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEventConditions()
   * @generated
   * @ordered
   */
  protected EList<EventConditions> eventConditions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EventConditionsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.EVENT_CONDITIONS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EVENT_CONDITIONS__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getIntValue()
  {
    return intValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIntValue(int newIntValue)
  {
    int oldIntValue = intValue;
    intValue = newIntValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EVENT_CONDITIONS__INT_VALUE, oldIntValue, intValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Unit getNameUnit()
  {
    return nameUnit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNameUnit(Unit newNameUnit, NotificationChain msgs)
  {
    Unit oldNameUnit = nameUnit;
    nameUnit = newNameUnit;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.EVENT_CONDITIONS__NAME_UNIT, oldNameUnit, newNameUnit);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNameUnit(Unit newNameUnit)
  {
    if (newNameUnit != nameUnit)
    {
      NotificationChain msgs = null;
      if (nameUnit != null)
        msgs = ((InternalEObject)nameUnit).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EVENT_CONDITIONS__NAME_UNIT, null, msgs);
      if (newNameUnit != null)
        msgs = ((InternalEObject)newNameUnit).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EVENT_CONDITIONS__NAME_UNIT, null, msgs);
      msgs = basicSetNameUnit(newNameUnit, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EVENT_CONDITIONS__NAME_UNIT, newNameUnit, newNameUnit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<EventConditions> getEventConditions()
  {
    if (eventConditions == null)
    {
      eventConditions = new EObjectContainmentEList<EventConditions>(EventConditions.class, this, MyDslPackage.EVENT_CONDITIONS__EVENT_CONDITIONS);
    }
    return eventConditions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.EVENT_CONDITIONS__NAME_UNIT:
        return basicSetNameUnit(null, msgs);
      case MyDslPackage.EVENT_CONDITIONS__EVENT_CONDITIONS:
        return ((InternalEList<?>)getEventConditions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.EVENT_CONDITIONS__NAME:
        return getName();
      case MyDslPackage.EVENT_CONDITIONS__INT_VALUE:
        return getIntValue();
      case MyDslPackage.EVENT_CONDITIONS__NAME_UNIT:
        return getNameUnit();
      case MyDslPackage.EVENT_CONDITIONS__EVENT_CONDITIONS:
        return getEventConditions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.EVENT_CONDITIONS__NAME:
        setName((String)newValue);
        return;
      case MyDslPackage.EVENT_CONDITIONS__INT_VALUE:
        setIntValue((Integer)newValue);
        return;
      case MyDslPackage.EVENT_CONDITIONS__NAME_UNIT:
        setNameUnit((Unit)newValue);
        return;
      case MyDslPackage.EVENT_CONDITIONS__EVENT_CONDITIONS:
        getEventConditions().clear();
        getEventConditions().addAll((Collection<? extends EventConditions>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.EVENT_CONDITIONS__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslPackage.EVENT_CONDITIONS__INT_VALUE:
        setIntValue(INT_VALUE_EDEFAULT);
        return;
      case MyDslPackage.EVENT_CONDITIONS__NAME_UNIT:
        setNameUnit((Unit)null);
        return;
      case MyDslPackage.EVENT_CONDITIONS__EVENT_CONDITIONS:
        getEventConditions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.EVENT_CONDITIONS__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslPackage.EVENT_CONDITIONS__INT_VALUE:
        return intValue != INT_VALUE_EDEFAULT;
      case MyDslPackage.EVENT_CONDITIONS__NAME_UNIT:
        return nameUnit != null;
      case MyDslPackage.EVENT_CONDITIONS__EVENT_CONDITIONS:
        return eventConditions != null && !eventConditions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", intValue: ");
    result.append(intValue);
    result.append(')');
    return result.toString();
  }

} //EventConditionsImpl
