/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Compute Info For In Built</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ComputeInfoForInBuilt#getOperationName <em>Operation Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ComputeInfoForInBuilt#getOperationParameter <em>Operation Parameter</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getComputeInfoForInBuilt()
 * @model
 * @generated
 */
public interface ComputeInfoForInBuilt extends EObject
{
  /**
   * Returns the value of the '<em><b>Operation Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operation Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation Name</em>' containment reference.
   * @see #setOperationName(OperationName)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getComputeInfoForInBuilt_OperationName()
   * @model containment="true"
   * @generated
   */
  OperationName getOperationName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ComputeInfoForInBuilt#getOperationName <em>Operation Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation Name</em>' containment reference.
   * @see #getOperationName()
   * @generated
   */
  void setOperationName(OperationName value);

  /**
   * Returns the value of the '<em><b>Operation Parameter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operation Parameter</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation Parameter</em>' attribute.
   * @see #setOperationParameter(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getComputeInfoForInBuilt_OperationParameter()
   * @model
   * @generated
   */
  int getOperationParameter();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ComputeInfoForInBuilt#getOperationParameter <em>Operation Parameter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation Parameter</em>' attribute.
   * @see #getOperationParameter()
   * @generated
   */
  void setOperationParameter(int value);

} // ComputeInfoForInBuilt
