/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event Conditions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.EventConditions#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.EventConditions#getIntValue <em>Int Value</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.EventConditions#getNameUnit <em>Name Unit</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.EventConditions#getEventConditions <em>Event Conditions</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEventConditions()
 * @model
 * @generated
 */
public interface EventConditions extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEventConditions_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.EventConditions#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Int Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Int Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int Value</em>' attribute.
   * @see #setIntValue(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEventConditions_IntValue()
   * @model
   * @generated
   */
  int getIntValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.EventConditions#getIntValue <em>Int Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int Value</em>' attribute.
   * @see #getIntValue()
   * @generated
   */
  void setIntValue(int value);

  /**
   * Returns the value of the '<em><b>Name Unit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name Unit</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Unit</em>' containment reference.
   * @see #setNameUnit(Unit)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEventConditions_NameUnit()
   * @model containment="true"
   * @generated
   */
  Unit getNameUnit();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.EventConditions#getNameUnit <em>Name Unit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Unit</em>' containment reference.
   * @see #getNameUnit()
   * @generated
   */
  void setNameUnit(Unit value);

  /**
   * Returns the value of the '<em><b>Event Conditions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.EventConditions}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Event Conditions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Conditions</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEventConditions_EventConditions()
   * @model containment="true"
   * @generated
   */
  EList<EventConditions> getEventConditions();

} // EventConditions
