/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interaction Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.InteractionSpec#getStructs <em>Structs</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.InteractionSpec#getInteractionName <em>Interaction Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInteractionSpec()
 * @model
 * @generated
 */
public interface InteractionSpec extends EObject
{
  /**
   * Returns the value of the '<em><b>Structs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Struct}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Structs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Structs</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInteractionSpec_Structs()
   * @model containment="true"
   * @generated
   */
  EList<Struct> getStructs();

  /**
   * Returns the value of the '<em><b>Interaction Name</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.InteractionName}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Interaction Name</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interaction Name</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInteractionSpec_InteractionName()
   * @model containment="true"
   * @generated
   */
  EList<InteractionName> getInteractionName();

} // InteractionSpec
