/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>OPERATOR</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.OPERATOR#getOpt <em>Opt</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOPERATOR()
 * @model
 * @generated
 */
public interface OPERATOR extends EObject
{
  /**
   * Returns the value of the '<em><b>Opt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Opt</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Opt</em>' attribute.
   * @see #setOpt(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOPERATOR_Opt()
   * @model
   * @generated
   */
  String getOpt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.OPERATOR#getOpt <em>Opt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Opt</em>' attribute.
   * @see #getOpt()
   * @generated
   */
  void setOpt(String value);

} // OPERATOR
